spring:
  application:
    name: config-server
  profiles:
    active: prod
  cloud:
    config:
      enabled: false
      server:
        git:
          uri: ${GITHUB_REPO_URL}
          default-label: main
          search-paths: '*/**'
          username: ${GITHUB_USERNAME}
          password: ${GITHUB_PASSWORD}
          clone-on-start: true
eureka:
  client:
    enabled: false
management:
  metrics:
    export:
      otlp:
        enabled: true
loki:
  url: ${LOKI_URL}
  username: ${LOKI_USERNAME}
  password: ${LOKI_PASSWORD}
server:
  port: 8888
